name: Notify site rebuild when data changes

on:
  push:
    branches: [main] # 或你的默认分支
    paths:
      - "all.mw" # 只关心数据目录的变更

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Call repository_dispatch on Repo B
        uses: peter-evans/repository-dispatch@v3 # 现成封装，省去手写 curl
        with:
          token: ${{ secrets.DISPATCH_TOKEN }} # PAT：repo + workflow 权限
          repository: Hemifuture/timeline_view # 目标库
          event-type: data-updated
          client-payload: |
            {
              "sha": "${{ github.sha }}",
              "ref": "${{ github.ref }}"
            }
